version: 2.1

parameters:
  java-version:
    type: string
    default: "17.0"
  os:
    type: string
    default: "linux"

executors:
  linux-java:
    parameters:
      java-version:
        type: string
    docker:
      - image: cimg/openjdk:<< parameters.java-version >>

  macos-java:
    parameters:
      java-version:
        type: string
    macos:
      xcode: 14.2  # versi macOS dengan JDK terpasang
    environment:
      JAVA_HOME: /Library/Java/JavaVirtualMachines/openjdk-<< parameters.java-version >>.jdk/Contents/Home

  windows-java:
    parameters:
      java-version:
        type: string
    machine:
      image: windows-server-2022-gui
    environment:
      JAVA_HOME: C:\openjdk-<< parameters.java-version >>

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
              sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports

  benchmark-jmh:
    parameters:
      java-version:
        type: string
      os:
        type: string
    executor:
      name: << include "os-executor" >>
      java-version: << parameters.java-version >>
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

commands:
  # Helper to resolve executor based on OS
  os-executor:
    parameters:
      java-version:
        type: string
      os:
        type: string
    return:
      <<#if (eq parameters.os "macos")>>macos-java<<else>><<#if (eq parameters.os "windows")>>windows-java<<else>>linux-java<</if>><</if>>

workflows:
  build-and-test:
    jobs:
      - test-java
      - benchmark-jmh:
          matrix:
            parameters:
              java-version: ["8.0", "11.0", "17.0"]
              os: ["linux", "macos", "windows"]