version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports

  benchmark-jmh:
    docker:
      - image: cimg/openjdk:{{ java_version }}
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - test-java
      - benchmark-jmh:
          matrix:
            parameters:
              java_version:
                - "8"
                - "9"
                - "10"
                - "11"
                - "12"
                - "13"
                - "14"
                - "15"
                - "16"
                - "17"
                - "18"
                - "19"
                - "20"
                - "21"
                - "22"
              os:
                - "ubuntu"
                - "windows"
                - "macos"
          docker:
            - image: cimg/openjdk:{{ java_version }}
