version: 2.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports

  benchmark-linux:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark on Linux
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

  benchmark-macos:
    macos:
      xcode: "14.2.0" # Xcode version, bisa diganti
    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            brew install openjdk@17
            sudo ln -sfn /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk
            export JAVA_HOME=/opt/homebrew/opt/openjdk@17
            echo 'export JAVA_HOME=/opt/homebrew/opt/openjdk@17' >> $BASH_ENV
      - run:
          name: Run JMH Benchmark on macOS
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

  benchmark-windows:
    machine:
      resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            choco install openjdk17
            setx JAVA_HOME "C:\Program Files\OpenJDK\openjdk-17"
      - run:
          name: Run JMH Benchmark on Windows
          command: ./gradlew.bat jmh
      - store_artifacts:
          path: build/reports

workflows:
  build-and-test:
    jobs:
      - test-java
      - benchmark-linux
      - benchmark-macos
      - benchmark-windows