version: 2.1

parameters:
  java-version:
    type: string
    default: "17"

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:<< parameters.java-version >>
    steps:
      - checkout
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results

  benchmark-linux:
    parameters:
      java-version:
        type: string
    docker:
      - image: cimg/openjdk:<< parameters.java-version >>
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark (Linux, Java << parameters.java-version >>)
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

  benchmark-macos:
    parameters:
      java-version:
        type: string
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: Install Java << parameters.java-version >>
          command: |
            brew install openjdk@<< parameters.java-version >>
            echo 'export JAVA_HOME=/opt/homebrew/opt/openjdk@<< parameters.java-version >>' >> $BASH_ENV
      - run:
          name: Run JMH Benchmark (macOS, Java << parameters.java-version >>)
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

  benchmark-windows:
    parameters:
      java-version:
        type: string
    machine:
      resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Install Java << parameters.java-version >>
          command: |
            choco install openjdk<< parameters.java-version >>
            setx JAVA_HOME "C:\Program Files\OpenJDK\openjdk-<< parameters.java-version >>"
      - run:
          name: Run JMH Benchmark (Windows, Java << parameters.java-version >>)
          command: ./gradlew.bat jmh
      - store_artifacts:
          path: build/reports

workflows:
  build-and-benchmark:
    jobs:
      - test-java
      - benchmark-linux:
          name: Benchmark - Linux (JDK << matrix.java-version >>)
          matrix:
            parameters:
              java-version: ["17.0", "21.0"]
      - benchmark-macos:
          name: Benchmark - macOS (JDK << matrix.java-version >>)
          matrix:
            parameters:
              java-version: ["17", "21"]
      - benchmark-windows:
          name: Benchmark - Windows (JDK << matrix.java-version >>)
          matrix:
            parameters:
              java-version: ["17"]
