version: 2.1

executors:
  linux-java:
    parameters:
      java-version:
        type: string
    docker:
      - image: cimg/openjdk:<< parameters.java-version >>

  macos-java:
    macos:
      xcode: 14.2
    environment:
      JAVA_HOME: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home

  windows-java:
    machine:
      image: windows-server-2022-gui
    environment:
      JAVA_HOME: "C:\\openjdk\\jdk-17"

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
              sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports

  benchmark-jmh-linux:
    parameters:
      java-version:
        type: string
    executor:
      name: linux-java
      java-version: << parameters.java-version >>
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

  benchmark-jmh-macos:
    executor: macos-java
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

  benchmark-jmh-windows:
    executor: windows-java
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark
          command: ./gradlew.bat jmh
      - store_artifacts:
          path: build/reports

workflows:
  build-and-test:
    jobs:
      - test-java
      - benchmark-jmh-linux:
          matrix:
            parameters:
              java-version: ["8.0", "11.0", "17.0"]
      - benchmark-jmh-macos
      - benchmark-jmh-windows
