version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports

  benchmark-jmh:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

  benchmark-jmh-matrix:
    docker:
      - image: cimg/openjdk:{{ .parameters.java_version }}  # Menggunakan versi Java dari parameter
    parameters:
      java_version:
        type: enum
        default: "17.0"
        enum:
          - "8.0"
          - "11.0"
          - "17.0"
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark on Java {{ .parameters.java_version }}
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

workflows:
  build-and-test:
    jobs:
      - test-java
      - benchmark-jmh
      - benchmark-jmh-matrix:
          matrix:
            parameters:
              java_version:
                - "8.0"
                - "11.0"
                - "17.0"
