version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
      - store_artifacts:
          path: build/reports

  benchmark-jmh:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

  benchmark-jmh-ubuntu:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark on Ubuntu
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

  benchmark-jmh-macos:
    macos:
      xcode: "12.5.0"
    steps:
      - checkout
      - run:
          name: Run JMH Benchmark on macOS
          command: ./gradlew jmh
      - store_artifacts:
          path: build/reports

#  benchmark-jmh-windows:
#    windows:
#      version: "20H2"
#    steps:
#      - checkout
#      - run:
#          name: Run JMH Benchmark on Windows
#          command: ./gradlew jmh
#      - store_artifacts:
#          path: build/reports

workflows:
  build-and-test:
    jobs:
      - test-java
      - benchmark-jmh
      - benchmark-jmh-ubuntu
      - benchmark-jmh-macos
#      - benchmark-jmh-windows